# ========================================
# Scenario A – n ≫ p, mixed strong/weak signals
# ----------------------------------------
# Purpose
# - Mid-sized regression where observations dominate features.
# - Highlights calibration when strong and weak signals coexist across many groups.
# - Moderate block correlation keeps shared-shrinkage helpful without degeneracy.
# ========================================

defaults: "configs/base.yaml"

data:
  n: 960
  p: 240
  G: 30
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.35
    block_size: 8
  signal:
    sparsity: 0.10
    strong_frac: 0.22
    beta_scale_strong: 1.7
    beta_scale_weak: 0.45
    group_sparsity: 0.6

model:
  name: "grwhs_gibbs"
  s_guess: 24
  tau0: 0.0036
  eta: 0.8

inference:
  gibbs:
    iters: 6000
    burn_in: 3000
    thin: 1
    adapt_slice: true
    jitter: 1.0e-8
