# ========================================
# Scenario D – p ≫ n with milder correlation
# ----------------------------------------
# Purpose
# - Complements Scenario B by lowering intra-block correlation.
# - Highlights effect of weaker sharing on automatic tau0 and group pooling.
# ========================================

defaults: "configs/base.yaml"

data:
  n: 360
  p: 900
  G: 36
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.30
    block_size: 25
  signal:
    sparsity: 0.13
    strong_frac: 0.18
    beta_scale_strong: 1.8
    beta_scale_weak: 0.40
    group_sparsity: 0.50

model:
  name: "grwhs_gibbs"
  s_guess: 117
  tau0: 0.0063
  eta: 0.65

inference:
  gibbs:
    iters: 6000
    burn_in: 3000
    thin: 1
    adapt_slice: true
    jitter: 1.0e-8
