# ========================================
# Scenario B (Classification) — high-dimensional sparse logistic regime
# ----------------------------------------
# Purpose
# - Mirrors Scenario B but swaps the Gaussian response for a binary outcome.
# - Provides a ready-to-run logistic regression benchmark with configurable logits.
# ========================================

defaults: "configs/base.yaml"

seed: 42
device: cpu
output_dir: outputs
task: classification

seeds:
  experiment: 42
  split: 42

standardization:
  X: unit_variance
  y_center: false

data:
  n: 48
  p: 360
  G: 15
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.45
    block_size: 24
  signal:
    sparsity: 0.11
    strong_frac: 0.25
    beta_scale_strong: 1.9
    beta_scale_weak: 0.50
    group_sparsity: 0.65
  classification:
    scale: 0.9          # Slightly temper logits to avoid separability
    bias: 0.0
    noise_std: 0.15     # Add mild jitter for more challenging decision boundaries
  test_ratio: 0.2
  val_ratio: 0.1
  loader:
    path_X: ""
    path_y: ""
    group_map: ""

model:
  name: logistic_regression
  logistic:
    penalty: "l2"
    C: 1.0
    solver: "lbfgs"
    max_iter: 400
    tol: 1.0e-4
    fit_intercept: true
    class_weight: null
    warm_start: false
    verbose: 0

experiments:
  repeats: 3
  save_posterior: false
  diagnostics: true
  metrics:
    regression:
      - RMSE
      - PredictiveLogLikelihood
      - Coverage90
      - IntervalWidth90
      - MeanKappa
      - EffectiveDoF
      - AUC-PR
      - F1
    classification:
      - ClassAccuracy
      - ClassF1
      - ClassAUROC
      - ClassAveragePrecision
      - ClassLogLoss
      - ClassBrier
      - AUC-PR
      - F1
  coverage_level: 0.9
  classification_threshold: 0.5
  runtime_profile: false

logging:
  level: INFO
  progress: true

checkpointing:
  enable: true
  keep_last: 1
  save_every_steps: 200

viz:
  dpi: 150
  style: default

io:
  run_dir: "D:\\grwhs\\outputs\\test_runs\\smoke-20251008-024320"
