# ========================================
# Scenario B – p ≫ n, mixed strong/weak signals
# ----------------------------------------
# Purpose
# - High-dimensional regime with many weak yet spread-out signals.
# - Tests automatic tau0 scaling when features far outnumber samples.
# - Uses variable group sizes and moderate correlation to stress group pooling.
# ========================================

defaults: "configs/base.yaml"

seed: 42
device: cpu
output_dir: outputs
task: regression

seeds:
  experiment: 42
  split: 42

standardization:
  X: unit_variance
  y_center: true

data:
  n: 48
  p: 360
  G: 15
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.45
    block_size: 24
  signal:
    sparsity: 0.11
    strong_frac: 0.25
    beta_scale_strong: 1.9
    beta_scale_weak: 0.50
    group_sparsity: 0.65
  classification:
    scale: 1.0
    bias: 0.0
    noise_std: 0.0
  noise_sigma: 1.0
  test_ratio: 0.2
  val_ratio: 0.1
  loader:
    path_X: ""
    path_y: ""
    group_map: ""

model:
  name: grwhs_gibbs
  c: 1.7
  s_guess: 16
  tau0: 0.008
  eta: 1.0
  size_adjust: true
  s0: 0.8
  iters: 8000

inference:
  gibbs:
    iters: 8000
    burn_in: 4000
    thin: 4
    adapt_slice: false
    jitter: 1.0e-06
    seed: 123
    slice_w: 0.15
  svi:
    steps: 4000
    lr: 0.01
    mc_samples: 3
    batch_size: 48
    natural_grad: true
    elbo_eval_every: 100
    clip_grad_norm: 10.0
    jitter: 1.0e-06
    seed: 123
    use_hutchinson: true
    hutchinson_samples: 12
    cg_tol: 0.001
    cg_maxiter: 200
    natgrad_damping: 0.001
    coupling_clip: 3.0
    cov_damping: 0.0

experiments:
  repeats: 3
  save_posterior: true
  diagnostics: true
  metrics:
    regression:
      - RMSE
      - PredictiveLogLikelihood
      - Coverage90
      - IntervalWidth90
      - MeanKappa
      - EffectiveDoF
      - AUC-PR
      - F1
    classification:
      - ClassAccuracy
      - ClassF1
      - ClassAUROC
      - ClassAveragePrecision
      - ClassLogLoss
      - ClassBrier
      - AUC-PR
      - F1
  coverage_level: 0.9
  classification_threshold: 0.5
  runtime_profile: false

logging:
  level: INFO
  progress: true

checkpointing:
  enable: true
  keep_last: 3
  save_every_steps: 200

viz:
  dpi: 150
  style: default


