# ========================================
# Scenario C — Dense weak signals, strong correlation
# ----------------------------------------
# Purpose
# - Stress-test stability and calibration when most coefficients are non-zero.
# - Strong correlation (compound symmetry) challenges over-shrinkage.
#
# Inference choice
# - Default: SVI (dense regime and larger p). For small data, you may try Gibbs
#   by setting model.name = "grwhs_gibbs", but expect longer runtime.
#
# Baselines
# - Compare against ridge (smooth shrinkage) and group_lasso (group-aware).
# ========================================

defaults: "configs/base.yaml"

data:
  n: 1200
  p: 600
  G: 60
  correlation:
    type: "cs"
    rho: 0.6
  signal:
    sparsity: 0.60            # Majority of coefficients active; emphasizes shrinkage smoothness
    strong_frac: 0.05         # Few truly strong effects atop a sea of weak coefficients
    beta_scale_strong: 0.8
    beta_scale_weak: 0.2

model:
  name: "grwhs_svi"
  c: 2.0                      # Wider slab to keep dense weak signals from collapsing to zero
  eta: 0.8                    # Loose group pooling so dense groups can stay active
  size_adjust: true
  tau0_heuristic:
    s: 200
    mode: "unit_variance"

inference:
  svi:
    steps: 4000
    lr: 8.0e-3
    batch_size: 512
    mc_samples: 4
    natural_grad: true
    elbo_eval_every: 100

experiments:
  repeats: 5
  metrics: ["mse", "r2"]
  threshold:
    type: "magnitude"
    value: 0.03

logging:
  level: "INFO"

