# ========================================
# Scenario C – n ≫ p with stronger block correlation
# ----------------------------------------
# Purpose
# - Same observation-rich regime as Scenario A but with tighter feature blocks.
# - Encourages borrowing strength across correlated groups while keeping weak signals identifiable.
# ========================================

defaults: "configs/base.yaml"

data:
  n: 780
  p: 210
  G: 26
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.50
    block_size: 8
  signal:
    sparsity: 0.12
    strong_frac: 0.30
    beta_scale_strong: 1.9
    beta_scale_weak: 0.55
    group_sparsity: 0.55

model:
  name: "grwhs_gibbs"
  s_guess: 25
  tau0: 0.0039
  eta: 0.65

inference:
  gibbs:
    iters: 6000
    burn_in: 3000
    thin: 1
    adapt_slice: true
    jitter: 1.0e-8
