# ========================================
# Scenario B — Mixed strong/weak signals, block correlation
# ----------------------------------------
# Purpose
# - Highlights calibration of shrinkage across strong and weak effects.
# - Moderate block correlation to reflect clustered features.
#
# Inference choice
# - Default: SVI for speed at p=500. For smaller data, switch to Gibbs by
#   setting model.name = "grwhs_gibbs".
#
# Baselines
# - Swap model.name to ridge | lasso | group_lasso | horseshoe | regularized_horseshoe
#   to compare calibration and selection.
# ========================================

defaults: "configs/base.yaml"

data:
  n: 1000
  p: 500
  G: 50
  correlation:
    type: "block"
    rho: 0.5
    block_size: 10
  signal:
    sparsity: 0.12          # Moderately sparse: retains a background of weak coefficients
    strong_frac: 0.10       # 10% of the active set uses beta_scale_strong; remainder follow beta_scale_weak
    beta_scale_strong: 2.0
    beta_scale_weak: 0.35

model:
  name: "grwhs_svi"
  c: 1.5
  eta: 0.6                  # Moderately loose group pooling to avoid over-shrinking weak signals
  size_adjust: true
  tau0_heuristic:
    s: 30
    mode: "unit_variance"

inference:
  svi:
    steps: 3000
    lr: 1.0e-2
    batch_size: 512
    mc_samples: 3
    natural_grad: true
    elbo_eval_every: 100

experiments:
  repeats: 5
  coverage_level: 0.9

logging:
  level: "INFO"
