# ========================================
# Scenario B – p ≫ n, mixed strong/weak signals
# ----------------------------------------
# Purpose
# - High-dimensional regime with many weak yet spread-out signals.
# - Tests automatic tau0 scaling when features far outnumber samples.
# - Uses variable group sizes and moderate correlation to stress group pooling.
# ========================================

defaults: "configs/base.yaml"

data:
  n: 420
  p: 1200
  G: 40
  group_sizes: "variable"
  correlation:
    type: "block"
    rho: 0.45
    block_size: 30
  signal:
    sparsity: 0.11
    strong_frac: 0.25
    beta_scale_strong: 1.9
    beta_scale_weak: 0.50
    group_sparsity: 0.65

model:
  name: "grwhs_gibbs"
  s_guess: 132
  tau0: 0.0060
  eta: 0.8

inference:
  gibbs:
    iters: 6000
    burn_in: 3000
    thin: 1
    adapt_slice: true
    jitter: 1.0e-8
