"""Compose 2x2 panels for top-k coefficient bar plots across SNR per scenario.

Looks for files generated by plot_coefficient_recovery.py with unique prefixes:
  <scenario>_snr<token>_coeff_bar_topk.png
and falls back to legacy name `coeff_bar_topk.png` if needed.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import matplotlib.image as mpimg  # noqa: E402


SNR_TOKENS = ["0p1", "0p5", "1p0", "3p0"]


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Compose top-k coefficient bar panels across SNR")
    p.add_argument("--scenario", required=True, choices=["sim_s1", "sim_s2", "sim_s3"], help="Scenario name")
    p.add_argument("--fig-root", type=Path, default=Path("outputs/figures"), help="Root of per-SNR figures")
    p.add_argument("--outdir", type=Path, default=None, help="Output dir (default: <fig-root>/<scenario>_panels)")
    p.add_argument("--top-k", type=int, default=40, help="Top-k used in the underlying bar plots (for title only)")
    return p.parse_args()


def _find_image(fig_root: Path, scenario: str, token: str) -> Path:
    base = fig_root / f"{scenario}_snr{token}_grrhs_vs_rhs" / "coefficients"
    pref = base / f"{scenario}_snr{token}_coeff_bar_topk.png"
    if pref.exists():
        return pref
    legacy = base / "coeff_bar_topk.png"
    if legacy.exists():
        return legacy
    raise FileNotFoundError(pref)


def main() -> None:
    args = _parse_args()
    outdir = args.outdir or (args.fig_root / f"{args.scenario}_panels")
    outdir.mkdir(parents=True, exist_ok=True)

    fig, axes = plt.subplots(2, 2, figsize=(14, 8))
    titles = {"0p1": "SNR=0.1", "0p5": "SNR=0.5", "1p0": "SNR=1.0", "3p0": "SNR=3.0"}
    for ax, tok in zip(axes.flat, SNR_TOKENS):
        path = _find_image(args.fig_root, args.scenario, tok)
        img = mpimg.imread(path)
        ax.imshow(img)
        ax.set_title(titles[tok])
        ax.axis("off")

    fig.suptitle(f"{args.scenario}: Top-{args.top_k} coefficients (Truth vs GRRHS vs RHS)", y=0.98)
    fig.tight_layout()
    out_path = outdir / f"{args.scenario}_snr_all_coeff_topk.png"
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] Coeff top-k panel written to {out_path}")


if __name__ == "__main__":
    main()
