name: "grouped_horseshoe"

model:
  name: "grouped_horseshoe"
  fit_intercept: true
  tau0: 1.0
  group_scale_prior: 1.0
  local_scale_prior: 1.0
  iters: 3000
  burnin: 1500
  thin: 1
  num_chains: 4
  jitter: 1.0e-08
  progress_bar: false
  seed: 2025
