# Sweep: explore correlation/mixture grid around base.yaml
name: mixed_signal_grid
output_dir: outputs/sweeps/mixed_signal_grid

variations:
  # rho in {0.30, 0.40, 0.50} crossed with three mixture profiles
  - name: rho30_profile_lo
    overrides:
      data:
        correlation:
          rho: 0.30
        signal:
          strong_frac: 0.15
          beta_scale_weak: 0.35
          group_sparsity: 0.70

  - name: rho30_profile_mid
    overrides:
      data:
        correlation:
          rho: 0.30
        signal:
          strong_frac: 0.22
          beta_scale_weak: 0.45
          group_sparsity: 0.60

  - name: rho30_profile_hi
    overrides:
      data:
        correlation:
          rho: 0.30
        signal:
          strong_frac: 0.30
          beta_scale_weak: 0.55
          group_sparsity: 0.50

  - name: rho40_profile_lo
    overrides:
      data:
        correlation:
          rho: 0.40
        signal:
          strong_frac: 0.15
          beta_scale_weak: 0.35
          group_sparsity: 0.70

  - name: rho40_profile_mid
    overrides:
      data:
        correlation:
          rho: 0.40
        signal:
          strong_frac: 0.22
          beta_scale_weak: 0.45
          group_sparsity: 0.60

  - name: rho40_profile_hi
    overrides:
      data:
        correlation:
          rho: 0.40
        signal:
          strong_frac: 0.30
          beta_scale_weak: 0.55
          group_sparsity: 0.50

  - name: rho50_profile_lo
    overrides:
      data:
        correlation:
          rho: 0.50
        signal:
          strong_frac: 0.15
          beta_scale_weak: 0.35
          group_sparsity: 0.70

  - name: rho50_profile_mid
    overrides:
      data:
        correlation:
          rho: 0.50
        signal:
          strong_frac: 0.22
          beta_scale_weak: 0.45
          group_sparsity: 0.60

  - name: rho50_profile_hi
    overrides:
      data:
        correlation:
          rho: 0.50
        signal:
          strong_frac: 0.30
          beta_scale_weak: 0.55
          group_sparsity: 0.50
