name: "real_covid19_trust_experts_methods"
output_dir: "outputs/sweeps/real_covid19_trust_experts"

common_config_files:
  - "../experiments/real_covid19_trust_experts.yaml"
  - "../overrides/real_data_fast_fair.yaml"

variations:
  - name: "trust_experts_grrhs"
    config_files:
      - "../methods/grrhs_regression.yaml"

  - name: "trust_experts_rhs"
    config_files:
      - "../methods/regularized_horseshoe.yaml"

  - name: "trust_experts_gigg"
    config_files:
      - "../methods/gigg.yaml"

  - name: "trust_experts_sgl"
    config_files:
      - "../methods/sparse_group_lasso.yaml"
      - "../overrides/sgl_real_fast.yaml"

  - name: "trust_experts_lasso"
    config_files:
      - "../methods/lasso.yaml"
      - "../overrides/lasso_real_fast.yaml"

  - name: "trust_experts_ridge"
    config_files:
      - "../methods/ridge.yaml"
