name: scenario_B_refined_s_guess_grid
output_dir: outputs/sweeps/scenario_B_refined_s_guess_grid

common_overrides:
  model:
    iters: 8000
  inference:
    gibbs:
      iters: 8000
      burn_in: 4000

variations:
  - name: sg12_c1.2_eta1.2
    overrides:
      model:
        s_guess: 12
        c: 1.2
        eta: 1.2
  - name: sg12_c1.2_eta1.5
    overrides:
      model:
        s_guess: 12
        c: 1.2
        eta: 1.5
  - name: sg12_c1.2_eta1.7
    overrides:
      model:
        s_guess: 12
        c: 1.2
        eta: 1.7
  - name: sg12_c1.2_eta2.0
    overrides:
      model:
        s_guess: 12
        c: 1.2
        eta: 2.0
  - name: sg12_c1.6_eta1.2
    overrides:
      model:
        s_guess: 12
        c: 1.6
        eta: 1.2
  - name: sg12_c1.6_eta1.5
    overrides:
      model:
        s_guess: 12
        c: 1.6
        eta: 1.5
  - name: sg12_c1.6_eta1.7
    overrides:
      model:
        s_guess: 12
        c: 1.6
        eta: 1.7
  - name: sg12_c1.6_eta2.0
    overrides:
      model:
        s_guess: 12
        c: 1.6
        eta: 2.0
  - name: sg12_c2.0_eta1.2
    overrides:
      model:
        s_guess: 12
        c: 2.0
        eta: 1.2
  - name: sg12_c2.0_eta1.5
    overrides:
      model:
        s_guess: 12
        c: 2.0
        eta: 1.5
  - name: sg12_c2.0_eta1.7
    overrides:
      model:
        s_guess: 12
        c: 2.0
        eta: 1.7
  - name: sg12_c2.0_eta2.0
    overrides:
      model:
        s_guess: 12
        c: 2.0
        eta: 2.0
  - name: sg18_c1.2_eta1.2
    overrides:
      model:
        s_guess: 18
        c: 1.2
        eta: 1.2
  - name: sg18_c1.2_eta1.5
    overrides:
      model:
        s_guess: 18
        c: 1.2
        eta: 1.5
  - name: sg18_c1.2_eta1.7
    overrides:
      model:
        s_guess: 18
        c: 1.2
        eta: 1.7
  - name: sg18_c1.2_eta2.0
    overrides:
      model:
        s_guess: 18
        c: 1.2
        eta: 2.0
  - name: sg18_c1.6_eta1.2
    overrides:
      model:
        s_guess: 18
        c: 1.6
        eta: 1.2
  - name: sg18_c1.6_eta1.5
    overrides:
      model:
        s_guess: 18
        c: 1.6
        eta: 1.5
  - name: sg18_c1.6_eta1.7
    overrides:
      model:
        s_guess: 18
        c: 1.6
        eta: 1.7
  - name: sg18_c1.6_eta2.0
    overrides:
      model:
        s_guess: 18
        c: 1.6
        eta: 2.0
  - name: sg18_c2.0_eta1.2
    overrides:
      model:
        s_guess: 18
        c: 2.0
        eta: 1.2
  - name: sg18_c2.0_eta1.5
    overrides:
      model:
        s_guess: 18
        c: 2.0
        eta: 1.5
  - name: sg18_c2.0_eta1.7
    overrides:
      model:
        s_guess: 18
        c: 2.0
        eta: 1.7
  - name: sg18_c2.0_eta2.0
    overrides:
      model:
        s_guess: 18
        c: 2.0
        eta: 2.0
  - name: sg22_c1.2_eta1.2
    overrides:
      model:
        s_guess: 22
        c: 1.2
        eta: 1.2
  - name: sg22_c1.2_eta1.5
    overrides:
      model:
        s_guess: 22
        c: 1.2
        eta: 1.5
  - name: sg22_c1.2_eta1.7
    overrides:
      model:
        s_guess: 22
        c: 1.2
        eta: 1.7
  - name: sg22_c1.2_eta2.0
    overrides:
      model:
        s_guess: 22
        c: 1.2
        eta: 2.0
  - name: sg22_c1.6_eta1.2
    overrides:
      model:
        s_guess: 22
        c: 1.6
        eta: 1.2
  - name: sg22_c1.6_eta1.5
    overrides:
      model:
        s_guess: 22
        c: 1.6
        eta: 1.5
  - name: sg22_c1.6_eta1.7
    overrides:
      model:
        s_guess: 22
        c: 1.6
        eta: 1.7
  - name: sg22_c1.6_eta2.0
    overrides:
      model:
        s_guess: 22
        c: 1.6
        eta: 2.0
  - name: sg22_c2.0_eta1.2
    overrides:
      model:
        s_guess: 22
        c: 2.0
        eta: 1.2
  - name: sg22_c2.0_eta1.5
    overrides:
      model:
        s_guess: 22
        c: 2.0
        eta: 1.5
  - name: sg22_c2.0_eta1.7
    overrides:
      model:
        s_guess: 22
        c: 2.0
        eta: 1.7
  - name: sg22_c2.0_eta2.0
    overrides:
      model:
        s_guess: 22
        c: 2.0
        eta: 2.0
  - name: sg28_c1.2_eta1.2
    overrides:
      model:
        s_guess: 28
        c: 1.2
        eta: 1.2
  - name: sg28_c1.2_eta1.5
    overrides:
      model:
        s_guess: 28
        c: 1.2
        eta: 1.5
  - name: sg28_c1.2_eta1.7
    overrides:
      model:
        s_guess: 28
        c: 1.2
        eta: 1.7
  - name: sg28_c1.2_eta2.0
    overrides:
      model:
        s_guess: 28
        c: 1.2
        eta: 2.0
  - name: sg28_c1.6_eta1.2
    overrides:
      model:
        s_guess: 28
        c: 1.6
        eta: 1.2
  - name: sg28_c1.6_eta1.5
    overrides:
      model:
        s_guess: 28
        c: 1.6
        eta: 1.5
  - name: sg28_c1.6_eta1.7
    overrides:
      model:
        s_guess: 28
        c: 1.6
        eta: 1.7
  - name: sg28_c1.6_eta2.0
    overrides:
      model:
        s_guess: 28
        c: 1.6
        eta: 2.0
  - name: sg28_c2.0_eta1.2
    overrides:
      model:
        s_guess: 28
        c: 2.0
        eta: 1.2
  - name: sg28_c2.0_eta1.5
    overrides:
      model:
        s_guess: 28
        c: 2.0
        eta: 1.5
  - name: sg28_c2.0_eta1.7
    overrides:
      model:
        s_guess: 28
        c: 2.0
        eta: 1.7
  - name: sg28_c2.0_eta2.0
    overrides:
      model:
        s_guess: 28
        c: 2.0
        eta: 2.0
  - name: sg32_c1.2_eta1.2
    overrides:
      model:
        s_guess: 32
        c: 1.2
        eta: 1.2
  - name: sg32_c1.2_eta1.5
    overrides:
      model:
        s_guess: 32
        c: 1.2
        eta: 1.5
  - name: sg32_c1.2_eta1.7
    overrides:
      model:
        s_guess: 32
        c: 1.2
        eta: 1.7
  - name: sg32_c1.2_eta2.0
    overrides:
      model:
        s_guess: 32
        c: 1.2
        eta: 2.0
  - name: sg32_c1.6_eta1.2
    overrides:
      model:
        s_guess: 32
        c: 1.6
        eta: 1.2
  - name: sg32_c1.6_eta1.5
    overrides:
      model:
        s_guess: 32
        c: 1.6
        eta: 1.5
  - name: sg32_c1.6_eta1.7
    overrides:
      model:
        s_guess: 32
        c: 1.6
        eta: 1.7
  - name: sg32_c1.6_eta2.0
    overrides:
      model:
        s_guess: 32
        c: 2.0
        eta: 2.0
  - name: sg32_c2.0_eta1.2
    overrides:
      model:
        s_guess: 32
        c: 2.0
        eta: 1.2
  - name: sg32_c2.0_eta1.5
    overrides:
      model:
        s_guess: 32
        c: 2.0
        eta: 1.5
  - name: sg32_c2.0_eta1.7
    overrides:
      model:
        s_guess: 32
        c: 2.0
        eta: 1.7
  - name: sg32_c2.0_eta2.0
    overrides:
      model:
        s_guess: 32
        c: 2.0
        eta: 2.0
