# Sweep to optimise GRwHS Gibbs hyperparameters for Scenario B
name: scenario_B_grwhs_search
output_dir: outputs/sweeps/scenario_B/grwhs_search

common_overrides:
  experiments:
    repeats: 1          # faster inner loop; rerun best config with repeats=3 later
    save_posterior: false
  logging:
    progress: false
  model:
    name: grwhs_gibbs
    iters: 8000
  inference:
    gibbs:
      iters: 8000
      burn_in: 3000
      thin: 1
      adapt_slice: true
      jitter: 1.0e-08
      slice_w: 0.15

variations:
  - name: base_reference
    overrides:
      model:
        tau0: 0.0128
        s_guess: 36
        eta: 0.65
        c: 1.2

  # tau0 = 0.0085 (stronger shrinkage, wider slab to compensate)
  - name: tau085_sg20_eta55
    overrides:
      model:
        tau0: 0.0085
        s_guess: 20
        eta: 0.55
        c: 1.7
  - name: tau085_sg20_eta70
    overrides:
      model:
        tau0: 0.0085
        s_guess: 20
        eta: 0.70
        c: 1.7
  - name: tau085_sg32_eta55
    overrides:
      model:
        tau0: 0.0085
        s_guess: 32
        eta: 0.55
        c: 1.7
  - name: tau085_sg32_eta70
    overrides:
      model:
        tau0: 0.0085
        s_guess: 32
        eta: 0.70
        c: 1.7
  - name: tau085_sg44_eta55
    overrides:
      model:
        tau0: 0.0085
        s_guess: 44
        eta: 0.55
        c: 1.7
  - name: tau085_sg44_eta70
    overrides:
      model:
        tau0: 0.0085
        s_guess: 44
        eta: 0.70
        c: 1.7

  # tau0 = 0.0105 (moderate shrinkage, mid slab)
  - name: tau105_sg20_eta55
    overrides:
      model:
        tau0: 0.0105
        s_guess: 20
        eta: 0.55
        c: 1.4
  - name: tau105_sg20_eta70
    overrides:
      model:
        tau0: 0.0105
        s_guess: 20
        eta: 0.70
        c: 1.4
  - name: tau105_sg32_eta55
    overrides:
      model:
        tau0: 0.0105
        s_guess: 32
        eta: 0.55
        c: 1.4
  - name: tau105_sg32_eta70
    overrides:
      model:
        tau0: 0.0105
        s_guess: 32
        eta: 0.70
        c: 1.4
  - name: tau105_sg44_eta55
    overrides:
      model:
        tau0: 0.0105
        s_guess: 44
        eta: 0.55
        c: 1.4
  - name: tau105_sg44_eta70
    overrides:
      model:
        tau0: 0.0105
        s_guess: 44
        eta: 0.70
        c: 1.4

  # tau0 = 0.0125 (slightly looser shrinkage, tighter slab)
  - name: tau125_sg20_eta55
    overrides:
      model:
        tau0: 0.0125
        s_guess: 20
        eta: 0.55
        c: 1.2
  - name: tau125_sg20_eta70
    overrides:
      model:
        tau0: 0.0125
        s_guess: 20
        eta: 0.70
        c: 1.2
  - name: tau125_sg32_eta55
    overrides:
      model:
        tau0: 0.0125
        s_guess: 32
        eta: 0.55
        c: 1.2
  - name: tau125_sg32_eta70
    overrides:
      model:
        tau0: 0.0125
        s_guess: 32
        eta: 0.70
        c: 1.2
  - name: tau125_sg44_eta55
    overrides:
      model:
        tau0: 0.0125
        s_guess: 44
        eta: 0.55
        c: 1.2
  - name: tau125_sg44_eta70
    overrides:
      model:
        tau0: 0.0125
        s_guess: 44
        eta: 0.70
        c: 1.2

  # tau0 = 0.0145 (light shrinkage, tight slab to encourage sparsity)
  - name: tau145_sg20_eta55
    overrides:
      model:
        tau0: 0.0145
        s_guess: 20
        eta: 0.55
        c: 0.95
  - name: tau145_sg20_eta70
    overrides:
      model:
        tau0: 0.0145
        s_guess: 20
        eta: 0.70
        c: 0.95
  - name: tau145_sg32_eta55
    overrides:
      model:
        tau0: 0.0145
        s_guess: 32
        eta: 0.55
        c: 0.95
  - name: tau145_sg32_eta70
    overrides:
      model:
        tau0: 0.0145
        s_guess: 32
        eta: 0.70
        c: 0.95
  - name: tau145_sg44_eta55
    overrides:
      model:
        tau0: 0.0145
        s_guess: 44
        eta: 0.55
        c: 0.95
  - name: tau145_sg44_eta70
    overrides:
      model:
        tau0: 0.0145
        s_guess: 44
        eta: 0.70
        c: 0.95
