# Sweep to tune Horseshoe (HS) and Regularized Horseshoe (RHS) baselines on Scenario B
name: scenario_B_hs_search
output_dir: outputs/sweeps/scenario_B/hs_search

common_overrides:
  experiments:
    repeats: 1
    save_posterior: false
  logging:
    progress: false
  inference:
    nuts:
      num_warmup: 1500
      num_samples: 1500
      num_chains: 2
      thinning: 1
  model:
    num_warmup: 1500
    num_samples: 1500
    num_chains: 2
    thinning: 1
    progress_bar: false

variations:
  # Horseshoe baseline (standard slab)
  - name: hs_scale04_sigma08_acc095
    overrides:
      model:
        name: horseshoe
        scale_global: 0.4
        sigma_scale: 0.8
        target_accept_prob: 0.95
  - name: hs_scale06_sigma08_acc099
    overrides:
      model:
        name: horseshoe
        scale_global: 0.6
        sigma_scale: 0.8
        target_accept_prob: 0.99
  - name: hs_scale08_sigma10_acc095
    overrides:
      model:
        name: horseshoe
        scale_global: 0.8
        sigma_scale: 1.0
        target_accept_prob: 0.95
  - name: hs_scale10_sigma12_acc099
    overrides:
      model:
        name: horseshoe
        scale_global: 1.0
        sigma_scale: 1.2
        target_accept_prob: 0.99
  - name: hs_scale12_sigma12_acc099
    overrides:
      model:
        name: horseshoe
        scale_global: 1.2
        sigma_scale: 1.2
        target_accept_prob: 0.99

  # Regularized horseshoe baseline (vary slab width + global scale)
  - name: rhs_scale06_slab05_acc095
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 0.6
        slab_scale: 0.5
        sigma_scale: 0.9
        target_accept_prob: 0.95
  - name: rhs_scale06_slab10_acc099
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 0.6
        slab_scale: 1.0
        sigma_scale: 0.9
        target_accept_prob: 0.99
  - name: rhs_scale08_slab10_acc095
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 0.8
        slab_scale: 1.0
        sigma_scale: 1.1
        target_accept_prob: 0.95
  - name: rhs_scale10_slab10_acc099
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 1.0
        slab_scale: 1.0
        sigma_scale: 1.1
        target_accept_prob: 0.99
  - name: rhs_scale10_slab15_acc099
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 1.0
        slab_scale: 1.5
        sigma_scale: 1.2
        target_accept_prob: 0.99
  - name: rhs_scale12_slab15_acc099
    overrides:
      model:
        name: regularized_horseshoe
        scale_global: 1.2
        slab_scale: 1.5
        sigma_scale: 1.2
        target_accept_prob: 0.99
