name: "sim_s1_six_models_hardpass_autotune"
output_dir: "outputs/sweeps/sim_s1_six_models_hardpass_autotune"

common_config_files:
  - "../experiments/sim_s1.yaml"
  - "../overrides/sim1_bayes_hardpass_autotune.yaml"

variations:
  - name: "grrhs"
    config_files:
      - "../methods/grrhs_regression.yaml"
  - name: "rhs"
    config_files:
      - "../methods/regularized_horseshoe.yaml"
  - name: "gigg"
    config_files:
      - "../methods/gigg.yaml"
  - name: "sgl"
    config_files:
      - "../methods/sparse_group_lasso.yaml"
  - name: "lasso"
    config_files:
      - "../methods/lasso.yaml"
  - name: "ridge"
    config_files:
      - "../methods/ridge.yaml"
