name: stageC_tau0half_coarse
output_dir: outputs/sweeps/stageC_tau0half_coarse
common_config_files:
- ../scenario_B_refined.yaml
common_overrides:
  model:
    iters: 8000
    tau0: 0.0046973765
  inference:
    gibbs:
      iters: 8000
      burn_in: 4000
  postprocess:
    debias:
      enabled: false
variations:
- name: c1.50_eta1.10
  overrides:
    model:
      c: 1.5
      eta: 1.1
      tau0: 0.0046973765
- name: c1.50_eta1.15
  overrides:
    model:
      c: 1.5
      eta: 1.15
      tau0: 0.0046973765
- name: c1.50_eta1.20
  overrides:
    model:
      c: 1.5
      eta: 1.2
      tau0: 0.0046973765
- name: c1.50_eta1.25
  overrides:
    model:
      c: 1.5
      eta: 1.25
      tau0: 0.0046973765
- name: c1.50_eta1.30
  overrides:
    model:
      c: 1.5
      eta: 1.3
      tau0: 0.0046973765
- name: c1.55_eta1.10
  overrides:
    model:
      c: 1.55
      eta: 1.1
      tau0: 0.0046973765
- name: c1.55_eta1.15
  overrides:
    model:
      c: 1.55
      eta: 1.15
      tau0: 0.0046973765
- name: c1.55_eta1.20
  overrides:
    model:
      c: 1.55
      eta: 1.2
      tau0: 0.0046973765
- name: c1.55_eta1.25
  overrides:
    model:
      c: 1.55
      eta: 1.25
      tau0: 0.0046973765
- name: c1.55_eta1.30
  overrides:
    model:
      c: 1.55
      eta: 1.3
      tau0: 0.0046973765
- name: c1.60_eta1.10
  overrides:
    model:
      c: 1.6
      eta: 1.1
      tau0: 0.0046973765
- name: c1.60_eta1.15
  overrides:
    model:
      c: 1.6
      eta: 1.15
      tau0: 0.0046973765
- name: c1.60_eta1.20
  overrides:
    model:
      c: 1.6
      eta: 1.2
      tau0: 0.0046973765
- name: c1.60_eta1.25
  overrides:
    model:
      c: 1.6
      eta: 1.25
      tau0: 0.0046973765
- name: c1.60_eta1.30
  overrides:
    model:
      c: 1.6
      eta: 1.3
      tau0: 0.0046973765
- name: c1.65_eta1.10
  overrides:
    model:
      c: 1.65
      eta: 1.1
      tau0: 0.0046973765
- name: c1.65_eta1.15
  overrides:
    model:
      c: 1.65
      eta: 1.15
      tau0: 0.0046973765
- name: c1.65_eta1.20
  overrides:
    model:
      c: 1.65
      eta: 1.2
      tau0: 0.0046973765
- name: c1.65_eta1.25
  overrides:
    model:
      c: 1.65
      eta: 1.25
      tau0: 0.0046973765
- name: c1.65_eta1.30
  overrides:
    model:
      c: 1.65
      eta: 1.3
      tau0: 0.0046973765
- name: c1.70_eta1.10
  overrides:
    model:
      c: 1.7
      eta: 1.1
      tau0: 0.0046973765
- name: c1.70_eta1.15
  overrides:
    model:
      c: 1.7
      eta: 1.15
      tau0: 0.0046973765
- name: c1.70_eta1.20
  overrides:
    model:
      c: 1.7
      eta: 1.2
      tau0: 0.0046973765
- name: c1.70_eta1.25
  overrides:
    model:
      c: 1.7
      eta: 1.25
      tau0: 0.0046973765
- name: c1.70_eta1.30
  overrides:
    model:
      c: 1.7
      eta: 1.3
      tau0: 0.0046973765
