name: scenario_B_refined_stageB_ce_debias
output_dir: outputs/sweeps/stageB_ce_debias
common_config_files:
- ../scenario_B_refined.yaml
common_overrides:
  model:
    iters: 20000
    tau0: 0.0093947529
  inference:
    gibbs:
      iters: 20000
      burn_in: 10000
  postprocess:
    debias:
      enabled: false
      selector: absbeta
      k_grid:
      - 10
      - 20
      - 30
      ridge_lam_grid:
      - 0.0
      - 0.01
      - 0.1
      - 1.0
variations:
- name: c1.4_eta1.0_debias0
  overrides:
    model:
      c: 1.4
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.4_eta1.0_debias1
  overrides:
    model:
      c: 1.4
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.4_eta1.1_debias0
  overrides:
    model:
      c: 1.4
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.4_eta1.1_debias1
  overrides:
    model:
      c: 1.4
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.4_eta1.2_debias0
  overrides:
    model:
      c: 1.4
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.4_eta1.2_debias1
  overrides:
    model:
      c: 1.4
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.4_eta1.3_debias0
  overrides:
    model:
      c: 1.4
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.4_eta1.3_debias1
  overrides:
    model:
      c: 1.4
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.4_eta1.4_debias0
  overrides:
    model:
      c: 1.4
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.4_eta1.4_debias1
  overrides:
    model:
      c: 1.4
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.5_eta1.0_debias0
  overrides:
    model:
      c: 1.5
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.5_eta1.0_debias1
  overrides:
    model:
      c: 1.5
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.5_eta1.1_debias0
  overrides:
    model:
      c: 1.5
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.5_eta1.1_debias1
  overrides:
    model:
      c: 1.5
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.5_eta1.2_debias0
  overrides:
    model:
      c: 1.5
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.5_eta1.2_debias1
  overrides:
    model:
      c: 1.5
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.5_eta1.3_debias0
  overrides:
    model:
      c: 1.5
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.5_eta1.3_debias1
  overrides:
    model:
      c: 1.5
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.5_eta1.4_debias0
  overrides:
    model:
      c: 1.5
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.5_eta1.4_debias1
  overrides:
    model:
      c: 1.5
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.6_eta1.0_debias0
  overrides:
    model:
      c: 1.6
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.6_eta1.0_debias1
  overrides:
    model:
      c: 1.6
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.6_eta1.1_debias0
  overrides:
    model:
      c: 1.6
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.6_eta1.1_debias1
  overrides:
    model:
      c: 1.6
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.6_eta1.2_debias0
  overrides:
    model:
      c: 1.6
      eta: 1.2
      tau0: 0.0046973765
    postprocess:
      debias:
        enabled: false
- name: c1.6_eta1.2_debias1
  overrides:
    model:
      c: 1.6
      eta: 1.2
      tau0: 0.0046973765
    postprocess:
      debias:
        enabled: true
- name: c1.6_eta1.3_debias0
  overrides:
    model:
      c: 1.6
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.6_eta1.3_debias1
  overrides:
    model:
      c: 1.6
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.6_eta1.4_debias0
  overrides:
    model:
      c: 1.6
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.6_eta1.4_debias1
  overrides:
    model:
      c: 1.6
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.7_eta1.0_debias0
  overrides:
    model:
      c: 1.7
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.7_eta1.0_debias1
  overrides:
    model:
      c: 1.7
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.7_eta1.1_debias0
  overrides:
    model:
      c: 1.7
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.7_eta1.1_debias1
  overrides:
    model:
      c: 1.7
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.7_eta1.2_debias0
  overrides:
    model:
      c: 1.7
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.7_eta1.2_debias1
  overrides:
    model:
      c: 1.7
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.7_eta1.3_debias0
  overrides:
    model:
      c: 1.7
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.7_eta1.3_debias1
  overrides:
    model:
      c: 1.7
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.7_eta1.4_debias0
  overrides:
    model:
      c: 1.7
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.7_eta1.4_debias1
  overrides:
    model:
      c: 1.7
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.8_eta1.0_debias0
  overrides:
    model:
      c: 1.8
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.8_eta1.0_debias1
  overrides:
    model:
      c: 1.8
      eta: 1.0
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.8_eta1.1_debias0
  overrides:
    model:
      c: 1.8
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.8_eta1.1_debias1
  overrides:
    model:
      c: 1.8
      eta: 1.1
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.8_eta1.2_debias0
  overrides:
    model:
      c: 1.8
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.8_eta1.2_debias1
  overrides:
    model:
      c: 1.8
      eta: 1.2
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.8_eta1.3_debias0
  overrides:
    model:
      c: 1.8
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.8_eta1.3_debias1
  overrides:
    model:
      c: 1.8
      eta: 1.3
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
- name: c1.8_eta1.4_debias0
  overrides:
    model:
      c: 1.8
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: false
- name: c1.8_eta1.4_debias1
  overrides:
    model:
      c: 1.8
      eta: 1.4
      tau0: 0.0093947529
    postprocess:
      debias:
        enabled: true
